### ISSUE TITLE
TestNG not working in my system.

### ISSUE THREAD

**Issue by Amitamon2** [tabhresh/Edureka_4th_March#6]
package com.Mod6;

import org.junit.BeforeClass;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class Driver_TestNG {
 
	
	WebDriver driver;
	
	@BeforeClass  
	public void openBrowser() {
		
		System.setProperty("webdriver.chrome.driver", "F:\\Edureka\\Course\\Drivers\\chromedriver.exe");
		driver = new ChromeDriver();
		
	}
	
	@BeforeTest (dependsOnMethods = "openBrowser")
	public void launchEdureka() {
		
		driver.get("https://www.edureka.co/");
		
	}
	
	@Test (dependsOnMethods = "launchEdureka")
	public void logIn() {
		
		driver.findElement(By.linkText("LogIn")).click();
		driver.findElement(By.cssSelector("#si_popup_passwd")).sendKeys("Amitankita@2");
		driver.findElement(By.cssSelector("#new_sign_up_mode > div > div > div.modal-body > div.login_video_frm.login-vd-box.sigin-new-division > form > button")).click();
	
	}
	
	@Test
	public void logOut() {
		
		driver.findElement(By.cssSelector("//*[@id=\"header-II\"]/section/nav/div/ul[2]/li[2]/a/img")).click();
		driver.findElement(By.linkText("Log Out")).click();
		
	}
	
	
	/*@AfterClass
	public void closeBrowser() {
		
		driver.close();
		
	}*/

}

Exception::

[RemoteTestNG] detected TestNG version 6.14.3
java.lang.NullPointerException
	at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:106)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:270)
	at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:376)
	at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:65)
	at org.testng.internal.TestNGMethodFinder.findConfiguration(TestNGMethodFinder.java:197)
	at org.testng.internal.TestNGMethodFinder.getBeforeTestConfigurationMethods(TestNGMethodFinder.java:88)
	at org.testng.TestClass.initMethods(TestClass.java:130)
	at org.testng.TestClass.init(TestClass.java:74)
	at org.testng.TestClass.<init>(TestClass.java:38)
	at org.testng.TestRunner.initMethods(TestRunner.java:389)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:192)
	at org.testng.remote.support.RemoteTestNG6_12$1.newTestRunner(RemoteTestNG6_12.java:33)
	at org.testng.remote.support.RemoteTestNG6_12$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_12.java:66)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:713)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by tabhresh** [comment]
As explained testNG conditions are only applicable in @Test Annotations

**Comment by Amitamon2** [comment]
I fixed it but still getting the same issue.

**Comment by tabhresh** [comment]
try running some other TestNG class and it should resolve if not raise a support ticket and they will get back to u!
